[package]
name = "annoirc"
version = "0.1.0"
authors = ["Thomas Hurst <tom@hur.st>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
irc = { path = "../rust-irc", features = ["tls-rust", "serde"], default-features = false }
tokio = { version = "0.2", features = ["full"] }
futures = "0.3.6"
slog = "2.5.2"
slog-async = "2.5.0"
slog-term = "2.6.0"
exitcode = "1.1.2"
reqwest = { version = "0.10.8", features = ["rustls-tls", "cookies", "gzip", "brotli"], default-features = false }
scraper = "0.12.0"
egg-mode-text = "1.14.7"
anyhow = "1.0.33"
serde_json = "1.0.59"
serde = "1.0.117"
egg-mode = { version = "0.15.0", features = ["rustls"], default-features = false }
ip_rfc = "0.1.0"
regex = "1.4.1"
timeago = { version = "0.2.1", features = ["chrono"] }
tera = "1.5.0"
log = "0.4.11"
leaky-bucket = "0.8.2"
itertools = "0.9.0"
lazy_static = "1.4.0"
url = "2.1.1"
clap = "3.0.0-beta.2"
toml = "0.5.7"
html-escape = "0.2.6"
