
# General command processing settings
[command]
## Maximum commands in flight at once
max_concurrency = 8

## Maximum runtime for any one command
max_runtime_secs = 10

## Retain previous results for this many seconds
cache_time_secs = 1800

## Retain up to this many previous results
cache_entries = 256

# Settings for URL handling
[url]
## Specify if http(s) scheme is required for url parsing
scheme_required = true

## Maximum URLs to process per PRIVMSG
max_per_message = 3

## HTTP request timeout - will never exceed general command timeout
timeout_secs = 10

## HTTP request body limit before giving up, 1-65535
max_kb = 256

## Maximum number of HTTP chunks to receive, 1-65535
max_chunks = 256

## If a request lands on a host that isn't globally routable (e.g. localhost)
## refuse to return any data.  This is currently only processed at the end of
## a request, after any redirections.
globally_routable_only = true

## User-Agent for requests
user_agent = "Mozilla/5.0 (FreeBSD 14.0; FreeBSD; x64; rv:81) Gecko/20100101 annoirc/81"

## Accept-Language header
## https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language
accept_language = "en,*;q=0.5"

## A list of regular expressions to ignore if they match a URL
## Use single quotes to avoid needing to double-escape the backslash
ignore_url_regex = ['imgur\.com/']

[omdb]
## Apply for API access at https://www.omdbapi.com/apikey.aspx
# api_key = "..."

[youtube]
## Apply for API access at https://console.cloud.google.com/apis/api/youtube.googleapis.com
# api_key = "..."
## Set to a 2-letter ISO 639-1 Code - https://www.loc.gov/standards/iso639-2/php/code_list.php
# lang = "en"

[wolfram]
## Apply for API access at https://developer.wolframalpha.com/
# app_id = "..."

[network.example]
nickname = "annobot"
alt_nicks = ["annobot_", "annobot__"]
username = "annobot"
realname = "Annoying Annotating Bot"
user_info = "Blame me on Freaky"
version = "No"
server = "irc.example"
port = 7000
use_tls = true
channels = ["#annobot"]
